[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "pudicus"
version = "0.1.1"
description = "A pluggable inspection gate for Git commits"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "PyYAML",
    "behave",
]

[tool.setuptools]
packages = ["pudicus"]

[project.scripts]
pudicus = "pudicus.cli:main"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "python -m pip install build && python -m build"
